FROM python:3.10-slim
WORKDIR /app

COPY backend/ai-engine/src/vectored/requirements.txt .
RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu \
 && pip install --no-cache-dir -r requirements.txt

COPY backend/ai-engine/src/vectored .
CMD ["python", "vector_service.py"]
