FROM rust:latest

WORKDIR /app

# Cache dependencies
COPY Cargo.toml Cargo.lock ./
RUN mkdir -p src/bin && echo "fn main() {}" > src/bin/main.rs
RUN cargo build

# Copy actual code
COPY . .

CMD ["cargo", "run"]